// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm-debugger.sequence.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    implementation(project(":kotlin-ide:common"))
    
    
    
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}