// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm-debugger.sequence.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    implementation(project(":kotlin-ide:common"))
    
    
    
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}