// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm-debugger.sequence.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("stream-debugger"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}