// GENERATED build.gradle.kts
// GENERATED BY kotlin.line-indent-provider.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("lib/resources_en"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}