// GENERATED build.gradle.kts
// GENERATED BY kotlin.line-indent-provider.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}

testsJar()