// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.allopen.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:maven"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:compiler-plugins:annotation-based-compiler-support"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("plugins/java/lib/java-api"))
    implementation(intellijPluginDep("plugins/java/lib/java_resources_en"))
    implementation(intellijPluginDep("plugins/gradle/lib/gradle-tooling-extension-api"))
    implementation(intellijPluginDep("plugins/gradle/lib/gradle-common"))
    implementation(project(":kotlin-ide:frontend-independent"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}