// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:resources-fir"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:frontend-api"))
    implementation(project(":kotlin-ide:frontend-fir"))
    implementation(project(":kotlin-ide:fir-low-level-api"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:compiler-plugins:sam-with-receiver"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("platform-api") })
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}