// GENERATED build.gradle.kts
// GENERATED BY kotlin.git.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(intellijPluginDep("git4idea"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}