// GENERATED build.gradle.kts
// GENERATED BY kotlin.git.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(intellijPluginDep("git4idea"))
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}