// GENERATED build.gradle.kts
// GENERATED BY kotlin.scripting-support.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeTest(":kotlin-ide:common")
    jpsLikeTest(":kotlin-ide:core")
    jpsLikeTest(":kotlin-ide:frontend-independent")
    jpsLikeTest(":kotlin-ide:idea")
    jpsLikeTest(":kotlin-ide:jvm")
    jpsLikeTest(":kotlin-ide:jvm-debugger:coroutines")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("intellij-dvcs") })
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core") })
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()