// GENERATED build.gradle.kts
// GENERATED BY kotlin.scripting-support.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    
    
    
    
    
    
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:jvm-debugger:coroutines"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    
    
    
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}