// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm-debugger.util.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:jvm-debugger:eval4j"))
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("plugins/java/lib/java-api"))
    implementation(intellijPluginDep("plugins/java/lib/java_resources_en"))
    implementation(intellijPluginDep("plugins/java/lib/java-impl"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}