// GENERATED build.gradle.kts
// GENERATED BY kotlin.repl.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:common")
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-ide-util-io") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("platform-core-ui") })
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}

testsJar()