// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm-debugger.test.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(project(":kotlin-ide:jvm-debugger:core"))
    implementation(project(":kotlin-ide:jvm-debugger:util"))
    implementation(project(":kotlin-ide:jvm-debugger:coroutines"))
    implementation(project(":kotlin-ide:jvm-debugger:evaluation"))
    implementation(project(":kotlin-ide:jvm-debugger:sequence"))
    implementation(project(":kotlin-ide:jvm-debugger:eval4j"))
    implementation(intellijPluginDep("lib/platform-api"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("plugins/java/lib/java-impl"))
    implementation(intellijPluginDep("plugins/java/lib/java_resources_en"))
    implementation(intellijPluginDep("plugins/stream-debugger/lib/stream-debugger"))
    implementation(intellijPluginDep("plugins/stream-debugger/lib/resources_en"))
    implementation(intellijPluginDep("plugins/java/lib/aether-dependency-resolver"))
    implementation(intellijPluginDep("plugins/java/lib/resources_en"))
    implementation(intellijPluginDep("plugins/DatabaseTools/lib/aether-dependency-resolver"))
    implementation(intellijPluginDep("plugins/DatabaseTools/lib/resources_en"))
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}