// GENERATED build.gradle.kts
// GENERATED BY kotlin.performance-tests.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeTest(":kotlin-ide:common")
    jpsLikeTest(":kotlin-ide:core")
    jpsLikeTest(":kotlin-ide:frontend-independent")
    jpsLikeTest(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeTest(":kotlin-ide:idea")
    jpsLikeTest(":kotlin-ide:gradle:gradle-idea")
    jpsLikeTest(":kotlin-ide:native")
    jpsLikeTest(":kotlin-ide:formatter")
    jpsLikeTest(":kotlin-ide:jps:jps-common")
    jpsLikeTest(":kotlin-ide:jvm")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("intellij-dvcs") })
    implementation(intellijPluginDep("gradle"))
    jpsLikeTest(":kotlin-ide:resources-descriptors")
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()