// GENERATED build.gradle.kts
// GENERATED BY kotlin.performance-tests.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(project(":kotlin-ide:native"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("intellij-dvcs"))
    implementation(intellijPluginDep("gradle"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}