// GENERATED build.gradle.kts
// GENERATED BY kotlin.scripting.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}