// GENERATED build.gradle.kts
// GENERATED BY kotlin.uast.uast-kotlin.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeTest(":kotlin-ide:common")
    jpsLikeTest(":kotlin-ide:core")
    jpsLikeTest(":kotlin-ide:frontend-independent")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("uast-tests") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()