// GENERATED build.gradle.kts
// GENERATED BY kotlin.gradle.gradle-native.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:native"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(intellijPluginDep("lib/platform-api"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("plugins/gradle-java/lib/gradle-java"))
    implementation(intellijPluginDep("plugins/gradle-java/lib/resources_en"))
    implementation(intellijPluginDep("lib/testFramework"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}