// GENERATED build.gradle.kts
// GENERATED BY kotlin.j2k.idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:j2k:old"))
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}