// GENERATED build.gradle.kts
// GENERATED BY kotlin.j2k.idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:j2k:old")
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    jpsLikeTest(":kotlin-ide:resources-descriptors")
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}

testsJar()