// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.scripting-ide-services.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("util"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("platform-api"))
    implementation(project(":kotlin-ide:frontend-independent"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}