// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.scripting.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("gradle"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}