// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir.fir-low-level-api.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    jpsLikeTest(":kotlin-ide:fir")
    
    jpsLikeTest(":kotlin-ide:resources-fir")
    jpsLikeTest(":kotlin-ide:frontend-fir")
    jpsLikeCompile(":kotlin-ide:frontend-api")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    jpsLikeTest(":kotlin-ide:idea")
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-api") })
    jpsLikeCompile(":kotlin-ide:core")
    implementation(intellijPluginDep("java"))
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeTest(":kotlin-ide:common")
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()