// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir-all-tests.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:resources-fir")
    jpsLikeCompile(":kotlin-ide:fir")
    jpsLikeCompile(":kotlin-ide:fir-low-level-api")
    jpsLikeCompile(":kotlin-ide:frontend-api")
    jpsLikeCompile(":kotlin-ide:frontend-fir")
}

sourceSets {
    "main" {
        
    }
    "test" {
        
    }
}

testsJar()