// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir-all-tests.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    implementation(project(":kotlin-ide:resources-fir"))
    implementation(project(":kotlin-ide:fir"))
    implementation(project(":kotlin-ide:fir-low-level-api"))
    implementation(project(":kotlin-ide:frontend-api"))
    implementation(project(":kotlin-ide:frontend-fir"))
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}