// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:jps:jps-common")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:core")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:formatter")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:util")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeCompile(":kotlin-ide:repl")
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijPluginDep("coverage"))
    implementation(intellijPluginDep("IntelliLang"))
    implementation(intellijDep(), { includeJars("bootstrap") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("testFramework") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("intellij-dvcs") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijPluginDep("java-decompiler"))
    implementation(intellijPluginDep("java-i18n"))
    implementation(intellijPluginDep("junit"))
    implementation(intellijPluginDep("properties"))
    implementation(intellijPluginDep("testng"))
    implementation(intellijDep(), { includeJars("intellij-xml") })
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}

testsJar()