// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:jvm-debugger:core"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:jvm-debugger:util"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:repl"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("coverage"))
    implementation(intellijPluginDep("IntelliLang"))
    implementation(intellijPluginDep("bootstrap"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("testFramework"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("intellij-dvcs"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("java-decompiler"))
    implementation(intellijPluginDep("java-i18n"))
    implementation(intellijPluginDep("junit"))
    implementation(intellijPluginDep("properties"))
    implementation(intellijPluginDep("testng"))
    implementation(intellijPluginDep("intellij-xml"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}