// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.kotlinx-serialization.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:jps:jps-common")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:maven")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-idea")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:annotation-based-compiler-support")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijPluginDep("gradle"))
    jpsLikeCompile(":kotlin-ide:frontend-independent")
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()