// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.kotlinx-serialization.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:maven"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(project(":kotlin-ide:compiler-plugins:annotation-based-compiler-support"))
    implementation(project(":kotlin-ide:test-framework"))
    
    
    
    implementation(project(":kotlin-ide:frontend-independent"))
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}