// GENERATED build.gradle.kts
// GENERATED BY kotlin.test-framework.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(intellijPluginDep("lib/testFramework-java"))
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("lib/platform-api"))
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}