// GENERATED build.gradle.kts
// GENERATED BY kotlin.test-framework.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeTest(":kotlin-ide:jps:jps-common")
    jpsLikeTest(":kotlin-ide:common")
    jpsLikeTest(":kotlin-ide:core")
    jpsLikeTest(":kotlin-ide:frontend-independent")
    jpsLikeTest(":kotlin-ide:idea")
    jpsLikeTest(":kotlin-ide:jvm")
    jpsLikeTest(":kotlin-ide:formatter")
    jpsLikeTest(":kotlin-ide:tests-common")
    implementation(intellijDep(), { includeJars("testFramework-java") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-api") })
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()