// GENERATED build.gradle.kts
// GENERATED BY kotlin.test-framework.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(intellijDep(), { includeJars("testFramework-java") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-api") })
}

sourceSets {
    "main" {
        
    }
    "test" {
        java.srcDir("test")
    }
}