// GENERATED build.gradle.kts
// GENERATED BY kotlin.project-wizard.cli.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:project-wizard:core")
    jpsLikeTest(":kotlin-ide:tests-common")
    implementation(intellijDep(), { includeJars("testFramework") })
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()