// GENERATED build.gradle.kts
// GENERATED BY kotlin.project-wizard.cli.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    
    
    implementation(project(":kotlin-ide:project-wizard:core"))
    implementation(project(":kotlin-ide:tests-common"))
    
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}