// GENERATED build.gradle.kts
// GENERATED BY kotlin.all-tests.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:allopen")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:annotation-based-compiler-support")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:kapt")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:kotlinx-serialization")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:noarg")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:sam-with-receiver")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:scripting")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:formatter")
    jpsLikeCompile(":kotlin-ide:git")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-idea")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-native")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:j2k:idea")
    jpsLikeCompile(":kotlin-ide:j2k:new")
    jpsLikeCompile(":kotlin-ide:j2k:old")
    jpsLikeCompile(":kotlin-ide:j2k:services")
    jpsLikeCompile(":kotlin-ide:jps:jps-common")
    jpsLikeCompile(":kotlin-ide:jps:jps-plugin")
    jpsLikeCompile(":kotlin-ide:jvm")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:core")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:coroutines")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:eval4j")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:evaluation")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:sequence")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:test")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:util")
    jpsLikeCompile(":kotlin-ide:maven")
    jpsLikeCompile(":kotlin-ide:native")
    jpsLikeCompile(":kotlin-ide:project-wizard:cli")
    jpsLikeCompile(":kotlin-ide:project-wizard:core")
    jpsLikeCompile(":kotlin-ide:project-wizard:idea")
    jpsLikeCompile(":kotlin-ide:repl")
    jpsLikeCompile(":kotlin-ide:scripting")
    jpsLikeCompile(":kotlin-ide:scripting-support")
    jpsLikeCompile(":kotlin-ide:test-framework")
    jpsLikeCompile(":kotlin-ide:tests-common")
    jpsLikeCompile(":kotlin-ide:uast:uast-kotlin")
    jpsLikeCompile(":kotlin-ide:uast:uast-kotlin-idea")
    jpsLikeCompile(":kotlin-ide:performance-tests")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:scripting-ide-services")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:line-indent-provider")
    jpsLikeTest(":kotlin-ide:resources-descriptors")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:parcelize")
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}

testsJar()