// GENERATED build.gradle.kts
// GENERATED BY kotlin.core.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(intellijPluginDep("platform-statistics"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("intellij-xml"))
    implementation(intellijPluginDep("platform-core-ui"))
}

sourceSets {
    "main" {
        java.srcDir("../analysis/src")
        resources.srcDir("../analysis/resources")
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}