// GENERATED build.gradle.kts
// GENERATED BY kotlin.completion.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("java"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}