// GENERATED build.gradle.kts
// GENERATED BY kotlin.project-wizard.idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:jps:jps-common")
    jpsLikeCompile(":kotlin-ide:jvm")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:formatter")
    jpsLikeCompile(":kotlin-ide:project-wizard:core")
    jpsLikeTest(":kotlin-ide:project-wizard:cli")
    jpsLikeTest(":kotlin-ide:gradle:gradle-idea")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-dvcs") })
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("maven"))
    implementation(intellijPluginDep("gradle"))
    implementation(intellijDep(), { includeJars("platform-core-ui") })
    jpsLikeTest(":kotlin-ide:resources-descriptors")
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()