// GENERATED build.gradle.kts
// GENERATED BY kotlin.project-wizard.idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:project-wizard:core"))
    implementation(project(":kotlin-ide:project-wizard:cli"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-dvcs") })
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("maven"))
    implementation(intellijPluginDep("gradle"))
    implementation(intellijDep(), { includeJars("platform-core-ui") })
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}