// GENERATED build.gradle.kts
// GENERATED BY kotlin.j2k.new.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:j2k:old"))
    implementation(project(":kotlin-ide:j2k:idea"))
    implementation(project(":kotlin-ide:j2k:services"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    
    implementation(project(":kotlin-ide:resources-descriptors"))
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}