// GENERATED build.gradle.kts
// GENERATED BY kotlin.j2k.new.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeTest(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:j2k:old")
    jpsLikeTest(":kotlin-ide:j2k:idea")
    jpsLikeTest(":kotlin-ide:j2k:services")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijPluginDep("java"))
    jpsLikeTest(":kotlin-ide:resources-descriptors")
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()