// GENERATED build.gradle.kts
// GENERATED BY kotlin.tests-common.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("util"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("bootstrap"))
    implementation(intellijPluginDep("java"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}