// GENERATED build.gradle.kts
// GENERATED BY kotlin.tests-common.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijDep(), { includeJars("util") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("bootstrap") })
    implementation(intellijPluginDep("java"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}