// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.annotation-based-compiler-support.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:maven"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(intellijPluginDep("lib/platform-api"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("plugins/maven/lib/maven"))
    implementation(intellijPluginDep("plugins/maven/lib/resources_en"))
    implementation(intellijPluginDep("plugins/gradle/lib/gradle-common"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:frontend-independent"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}