// GENERATED build.gradle.kts
// GENERATED BY kotlin.maven.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("lib/platform-api"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("plugins/java/lib/java-impl"))
    implementation(intellijPluginDep("plugins/java/lib/java_resources_en"))
    implementation(intellijPluginDep("plugins/maven/lib/maven"))
    implementation(intellijPluginDep("plugins/maven/lib/resources_en"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}