// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.sam-with-receiver.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:maven")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-idea")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeCompile(":kotlin-ide:compiler-plugins:annotation-based-compiler-support")
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("gradle"))
    jpsLikeCompile(":kotlin-ide:frontend-independent")
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}

testsJar()