// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.parcelize.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeTest(":kotlin-ide:compiler-plugins:scripting")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeCompile(":kotlin-ide:common")
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("gradle"))
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("platform-objectSerializer-annotations") })
    jpsLikeCompile(":kotlin-ide:frontend-independent")
}

sourceSets {
    "main" {
        resources.srcDir("resources")
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()