// GENERATED build.gradle.kts
// GENERATED BY kotlin.compiler-plugins.parcelize.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:compiler-plugins:scripting"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:common"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("gradle"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("platform-objectSerializer-annotations"))
    implementation(project(":kotlin-ide:frontend-independent"))
}

sourceSets {
    "main" {
        resources.srcDir("resources")
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}