// GENERATED build.gradle.kts
// GENERATED BY kotlin.native.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("lib/testFramework"))
    implementation(intellijPluginDep("plugins/java/lib/java-api"))
    implementation(intellijPluginDep("plugins/java/lib/java_resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("plugins/java/lib/java-impl"))
    implementation(intellijPluginDep("plugins/gradle/lib/gradle-common"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        java.srcDir("gen")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}