// GENERATED build.gradle.kts
// GENERATED BY kotlin.native.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:jvm")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:jps:jps-common")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeTest(":kotlin-ide:tests-common")
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("testFramework") })
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("gradle"))
    jpsLikeTest(":kotlin-ide:resources-descriptors")
}

sourceSets {
    "main" {
        java.srcDir("src")
        java.srcDir("gen")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()