// GENERATED build.gradle.kts
// GENERATED BY kotlin.native.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("testFramework") })
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("gradle"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        java.srcDir("gen")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}