// GENERATED build.gradle.kts
// GENERATED BY kotlin.uast.uast-kotlin-idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:uast:uast-kotlin"))
    implementation(intellijPluginDep("lib/platform-util-ex"))
    implementation(intellijPluginDep("lib/platform-impl"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("lib/platform-api"))
    implementation(intellijPluginDep("plugins/java/lib/java-api"))
    implementation(intellijPluginDep("plugins/java/lib/java_resources_en"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}