// GENERATED build.gradle.kts
// GENERATED BY kotlin.uast.uast-kotlin-idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:uast:uast-kotlin"))
    implementation(intellijDep(), { includeJars("platform-util-ex") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijPluginDep("java"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}