// GENERATED build.gradle.kts
// GENERATED BY kotlin.uast.uast-kotlin-idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:uast:uast-kotlin"))
    
    
    
    
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        
    }
}