// GENERATED build.gradle.kts
// GENERATED BY kotlin.j2k.services.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:j2k:old"))
    implementation(project(":kotlin-ide:j2k:new"))
    implementation(project(":kotlin-ide:j2k:idea"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:jvm-debugger:sequence"))
    
    
    
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}