// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir.frontend-independent.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("intellij-xml") })
    implementation(intellijDep(), { includeJars("platform-core-ui") })
    jpsLikeTest(":kotlin-ide:tests-common")
}

sourceSets {
    "main" {
        resources.srcDir("resources-en")
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()