// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir.frontend-independent.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    
    
    
    
    
    
    
    
    implementation(project(":kotlin-ide:tests-common"))
}

sourceSets {
    "main" {
        resources.srcDir("resources-en")
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}