// GENERATED build.gradle.kts
// GENERATED BY kotlin.fir.frontend-independent.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("intellij-xml"))
    implementation(intellijPluginDep("platform-core-ui"))
    implementation(project(":kotlin-ide:tests-common"))
}

sourceSets {
    "main" {
        resources.srcDir("resources-en")
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}