// GENERATED build.gradle.kts
// GENERATED BY kotlin.generators.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:jvm-debugger:test")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:fir")
    jpsLikeCompile(":kotlin-ide:scripting-support")
    jpsLikeCompile(":kotlin-ide:maven")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-idea")
    jpsLikeCompile(":kotlin-ide:project-wizard:cli")
    jpsLikeCompile(":kotlin-ide:project-wizard:idea")
    jpsLikeCompile(":kotlin-ide:j2k:old")
    jpsLikeCompile(":kotlin-ide:j2k:new")
    jpsLikeCompile(":kotlin-ide:jps:jps-plugin")
    jpsLikeTest(":kotlin-ide:frontend-fir")
    jpsLikeTest(":kotlin-ide:fir-low-level-api")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    jpsLikeTest(":kotlin-ide:compiler-plugins:kotlinx-serialization")
    jpsLikeTest(":kotlin-ide:performance-tests")
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijPluginDep("java"))
    jpsLikeTest(":kotlin-ide:common")
    jpsLikeTest(":kotlin-ide:compiler-plugins:parcelize")
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()