// GENERATED build.gradle.kts
// GENERATED BY kotlin.generators.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    
    
    implementation(project(":kotlin-ide:jvm-debugger:test"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:fir"))
    implementation(project(":kotlin-ide:scripting-support"))
    implementation(project(":kotlin-ide:maven"))
    implementation(project(":kotlin-ide:gradle:gradle-idea"))
    implementation(project(":kotlin-ide:project-wizard:cli"))
    implementation(project(":kotlin-ide:project-wizard:idea"))
    implementation(project(":kotlin-ide:j2k:old"))
    implementation(project(":kotlin-ide:j2k:new"))
    implementation(project(":kotlin-ide:jps:jps-plugin"))
    implementation(project(":kotlin-ide:frontend-fir"))
    implementation(project(":kotlin-ide:fir-low-level-api"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(project(":kotlin-ide:compiler-plugins:kotlinx-serialization"))
    implementation(project(":kotlin-ide:performance-tests"))
    
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:compiler-plugins:parcelize"))
}

sourceSets {
    "main" {
        java.srcDir("src")
    }
    "test" {
        java.srcDir("test")
    }
}