// GENERATED build.gradle.kts
// GENERATED BY kotlin.gradle.gradle-idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:jvm"))
    implementation(project(":kotlin-ide:idea"))
    implementation(project(":kotlin-ide:formatter"))
    implementation(project(":kotlin-ide:gradle:gradle-tooling"))
    implementation(project(":kotlin-ide:jvm-debugger:core"))
    implementation(project(":kotlin-ide:jvm-debugger:coroutines"))
    implementation(project(":kotlin-ide:native"))
    implementation(project(":kotlin-ide:gradle:gradle-native"))
    implementation(project(":kotlin-ide:compiler-plugins:kapt"))
    implementation(project(":kotlin-ide:compiler-plugins:scripting"))
    implementation(project(":kotlin-ide:project-wizard:idea"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("platform-objectSerializer-annotations"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("platform-api"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("Groovy"))
    implementation(intellijPluginDep("junit"))
    implementation(intellijPluginDep("testng"))
    implementation(intellijPluginDep("gradle-java"))
    implementation(intellijPluginDep("gradle"))
    implementation(intellijPluginDep("platform-core-ui"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}