// GENERATED build.gradle.kts
// GENERATED BY kotlin.gradle.gradle-idea.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    jpsLikeCompile(":kotlin-ide:common")
    jpsLikeCompile(":kotlin-ide:core")
    jpsLikeCompile(":kotlin-ide:frontend-independent")
    jpsLikeCompile(":kotlin-ide:jps:jps-common")
    jpsLikeCompile(":kotlin-ide:jvm")
    jpsLikeCompile(":kotlin-ide:idea")
    jpsLikeCompile(":kotlin-ide:formatter")
    jpsLikeCompile(":kotlin-ide:gradle:gradle-tooling")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:core")
    jpsLikeCompile(":kotlin-ide:jvm-debugger:coroutines")
    jpsLikeCompile(":kotlin-ide:native")
    jpsLikeTest(":kotlin-ide:gradle:gradle-native")
    jpsLikeRuntime(":kotlin-ide:compiler-plugins:kapt")
    jpsLikeRuntime(":kotlin-ide:compiler-plugins:scripting")
    jpsLikeRuntime(":kotlin-ide:project-wizard:idea")
    jpsLikeTest(":kotlin-ide:tests-common")
    jpsLikeTest(":kotlin-ide:test-framework")
    implementation(intellijDep(), { includeJars("platform-objectSerializer-annotations") })
    implementation(intellijDep(), { includeJars("platform-impl") })
    implementation(intellijDep(), { includeJars("resources_en") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
    implementation(intellijDep(), { includeJars("platform-api") })
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("Groovy"))
    implementation(intellijPluginDep("junit"))
    implementation(intellijPluginDep("testng"))
    implementation(intellijPluginDep("gradle-java"))
    implementation(intellijPluginDep("gradle"))
    implementation(intellijDep(), { includeJars("platform-core-ui") })
    jpsLikeTest(":kotlin-ide:resources-descriptors")
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}

testsJar()