// GENERATED build.gradle.kts
// GENERATED BY kotlin.jvm-debugger.core.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:core"))
    implementation(project(":kotlin-ide:frontend-independent"))
    implementation(project(":kotlin-ide:jvm-debugger:eval4j"))
    implementation(project(":kotlin-ide:jvm-debugger:util"))
    implementation(intellijPluginDep("platform-impl"))
    implementation(intellijPluginDep("resources_en"))
    implementation(intellijPluginDep("java"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("platform-core-ui"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        
    }
}