// GENERATED build.gradle.kts
// GENERATED BY kotlin.jps-plugin.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    
    
    
    
    
    
    
    
    
    
    
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    
    
    
    
    
    
    implementation(project(":kotlin-ide:resources-descriptors"))
}

//sourceSets {
//    "main" {
//        projectDefault()
//        java.srcDir("../idea-analysis/src")
//        resources.srcDir("../idea-analysis/resources")
//    }
//    "test" {}
//}