// GENERATED build.gradle.kts
// GENERATED BY kotlin.jps-plugin.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(project(":kotlin-ide:jps:jps-common"))
    implementation(project(":kotlin-ide:common"))
    implementation(project(":kotlin-ide:tests-common"))
    implementation(project(":kotlin-ide:test-framework"))
    implementation(intellijPluginDep("lib/platform-api"))
    implementation(intellijPluginDep("lib/resources_en"))
    implementation(intellijPluginDep("intellij-core"))
    implementation(intellijPluginDep("intellij-core-analysis-deprecated"))
    implementation(intellijPluginDep("plugins/java/lib/jps-builders"))
    implementation(intellijPluginDep("plugins/java/lib/resources_en"))
    implementation(intellijPluginDep("lib/jps-model"))
    implementation(intellijPluginDep("plugins/devkit/lib/devkit-jps-plugin"))
    implementation(project(":kotlin-ide:resources-descriptors"))
}

sourceSets {
    "main" {
        java.srcDir("src")
        resources.srcDir("resources")
    }
    "test" {
        java.srcDir("test")
    }
}