// GENERATED build.gradle.kts
// GENERATED BY kotlin.util.compiler-classpath.iml
// USE `./gradlew generateGradleByIml` TO REGENERATE THIS FILE

plugins {
    kotlin("jvm")
    id("jps-compatible")
}

dependencies {
    
    implementation(intellijPluginDep("java"))
    implementation(intellijDep(), { includeJars("intellij-core") })
    implementation(intellijDep(), { includeJars("intellij-core-analysis-deprecated") })
}

sourceSets {
    "main" {
        java.srcDir("../../tools/kotlin-compiler-classpath/src")
    }
    "test" {
        
    }
}

testsJar()